version: "3"
services:
  web-dev:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - web

networks:
  web:
    external: true
